apiVersion: v1
kind: Service
metadata:
  name: datanodes
  labels:
    app: datanode
spec:
  clusterIP: None
  ports:
  - port: 80
  selector:
    app: datanode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
spec:
  serviceName: "datanodes"
  podManagementPolicy: "Parallel"
  replicas: 2
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: nctweb/hadoop:0.0.1
        imagePullPolicy: Always
        command: ["./entry-point"]
        volumeMounts:
        - name: secret
          mountPath: /secret
      
      volumes:
      - name: secret
        secret:
          secretName: data-node-secret
